
version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3
#    environment:
#        - MONGO_INITDB_ROOT_USERNAME=farmbot-weather-admin
#        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
        - ./mongo-data/:/data/db
    command: mongod
